name: 'Multi-Cloud Infra Deployment'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform (${{ matrix.cloud }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud: [aws, azure, gcp]
    
    # Environment variables for Terraform and Cloud Providers
    env:
      # AWS Credentials
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'
      
      # Azure Credentials
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      
      # Terraform Variables
      TF_VAR_aws_alb_sg_id: ${{ secrets.TF_VAR_AWS_ALB_SG_ID }}
      TF_VAR_aws_ec2_sg_id: ${{ secrets.TF_VAR_AWS_EC2_SG_ID }}
      TF_VAR_aws_db_sg_id: ${{ secrets.TF_VAR_AWS_DB_SG_ID }}
      TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}
      TF_VAR_gcp_project_id: ${{ secrets.TF_VAR_GCP_PROJECT_ID }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}

    defaults:
      run:
        working-directory: ./core-infra/${{ matrix.cloud }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Google Cloud Auth
      if: matrix.cloud == 'gcp'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false
      continue-on-error: false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
